server:
  port: 8069

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://smartheal.vercel.app, http://localhost:3000"
            allowedMethods: "GET, POST, PUT, DELETE"
            allowedHeaders: "Authorization, Content-Type"
            routes:
              - id: user-service
                uri: https://smarth-user-service.azurewebsites.net/
                predicates:
                  - Path=/user-service/**

              - id: result-service
                uri: https://smart-resultados.azurewebsites.net/
                predicates:
                  - Path=/resultado/**

              - id: validation-service
                uri: http://localhost:8004
                predicates:
                  - Path=/valoracion/**




